# Variables

CXX = g++
CXXFLAGS = -Wall

# files
MAIN = main.cc
DISPLAYS = forecast-display.cc statistics-display.cc current-conditions-display.cc
DATA = weather-data.cc

all:
	${CXX} ${CXXFLAGS} -std=c++14 ${MAIN} ${DATA} ${DISPLAYS}
